title: "Noodlefishh"
#description: "Field notes on security, code and research"
description_short: "Personal blog"
hero_title: "Field Notes On Security, Code and Research"
url: "https://noodlefishh.github.io"
baseurl: ""
lang: en

# Author
author:
  name: "Noodlefishh"
  email: "noodlefishh@pm.me"

# Social links
github_username: Noodlefishh


# Tags displayed in the hero
featured_tags:
  - Application Security
  - AI
  - Bug Bounty
  - open-source
  - OSINT

# Jekyll
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules